Added references to publications to README
UPPAALModelChecker/UCDD pull request #20
Opened 2022-06-19 18:32 UTC by mikucionisaau

2022-06-20 06:47 UTC, RasmusRendal requested changes

2022-06-20 06:47 UTC, RasmusRendal commented on README.md
> +*Clock Difference Diagrams* (CDD), a [BDD](https://en.wikipedia.org/wiki/Binary_decision_diagram)-like
```suggestion
*Clock Difference Diagrams* (CDD), is a [BDD](https://en.wikipedia.org/wiki/Binary_decision_diagram)-like
```

2022-06-20 06:47 UTC, RasmusRendal commented on README.md
> +It is shown that all set-theoretic operations including inclusion checking may be carried out effiiently on Clock Difference Diagrams.
```suggestion
It is shown that all set-theoretic operations including inclusion checking may be carried out efficiently on Clock Difference Diagrams.
```

2022-06-20 06:47 UTC, RasmusRendal commented on README.md
> +for nine industrial examples the savings are in average 42% with moderate increase in runtime.
```suggestion
Experimental results demonstrate significant space-savings. For instance, in nine industrial examples the space-savings are on average 42%, and with a moderate increase in runtime.
```

2022-06-21 06:07 UTC, yrke approved these changes

2022-06-21 06:22 UTC, RasmusRendal approved these changes

2022-06-21 12:19 UTC, merged